// Package store is the brain's SQLite persistence — the desired-state source
// of truth (CONTROL_PLANE.md, APP_LIFECYCLE.md). Skeleton scope: the app
// instances table only. Users, sessions, audit, etc. land later.
package store

import (
	"database/sql"
	"errors"
	"fmt"
	"log/slog"
	"strings"
	"time"

	_ "modernc.org/sqlite"
)

// Instance is one installed app (a compose project, APP_LIFECYCLE.md).
//
// Every instance is owner-scoped (DASHBOARD.md # the apps model). A household
// instance is admin-owned on behalf of everyone and takes the bare slug; a
// personal instance is owned by one user and takes the `<slug>--<user>` slug.
// OwnerUserID is a plain reference (no FK): user deletion vs. owned instances
// is unspecced (NEXT.md), so we don't couple deleteUser to ownership yet.
type Instance struct {
	ID          string
	ManifestID  string
	Name        string
	Slug        string
	Version     string
	State       string // installing | running | stopped | failed | uninstalling
	MDNSName    string
	OwnerUserID string
	Scope       string // ScopeHousehold | ScopePersonal
	// ServiceUID/GID is the dedicated app-service identity allocated for a
	// folderless `service_user: true` instance (APP_ISOLATION.md # Runtime
	// identity & data ownership). 0 = none — allocated values are always in
	// the reserved band (≥ protocol.AppServiceUIDMin), never root. Persisted
	// so the identity is stable across container recreations and releasable
	// at uninstall.
	ServiceUID int
	ServiceGID int
	// PendingRecreate marks a running instance whose committed override/.env was
	// changed by an env-restamping edit (config or mail) but whose follow-up
	// `compose up` failed, leaving its container on stale env. The reconcile pass
	// retries the recreate while it is set, then clears it (#268).
	PendingRecreate bool
	// Exposure is the per-app access gate for the hosted profile (#306,
	// ENVIRONMENT.md # Public-by-default): ExposureRestricted routes the app
	// behind the box's forward-auth (owner-only), ExposurePublic serves it
	// anonymously. New hosted installs default to ExposureRestricted; the
	// appliance is always ExposurePublic (it has no public app subdomains, so the
	// forward-auth wrap never applies there).
	Exposure  string
	CreatedAt time.Time
}

const (
	ScopeHousehold = "household"
	ScopePersonal  = "personal"
)

const (
	// ExposurePublic serves the app's route as a plain reverse-proxy (the
	// appliance's only mode; the hosted opt-out). ExposureRestricted wraps it in
	// the box forward-auth gate (hosted owner-only). See ENVIRONMENT.md #306.
	ExposurePublic     = "public"
	ExposureRestricted = "restricted"
)

// User is a moose dashboard account. The brain mirrors a Linux account
// (USERS_AND_GROUPS.md); the *password* lives in PAM via host-agent, never
// in this row. `recovery_hash` is set only for admins (AUTH.md # Recovery).
type User struct {
	ID       string
	Username string
	// DisplayName is what every surface shows. Mutable: a person may rename
	// themselves at any time, and doing so never touches Username, the home
	// directory, or file ownership (FIRST_RUN.md # Identity & display names).
	DisplayName  string
	Role         string // "admin" | "member"
	RecoveryHash string // argon2id of recovery code; empty for non-admin
	CreatedAt    time.Time
}

const (
	RoleAdmin  = "admin"
	RoleMember = "member"
)

// Session is an issued dashboard session. Tokens are opaque random bytes,
// generated by the auth package and used as the cookie value (AUTH.md #
// Sessions). `last_seen_at` is updated on each authenticated request so the
// session can age out independently of issue time.
type Session struct {
	Token         string
	UserID        string
	CreatedAt     time.Time
	LastSeenAt    time.Time
	ExpiresAt     time.Time // absolute hard cap (90 days from issue)
	ElevatedUntil time.Time // zero value means not elevated
}

// ErrConflict signals a uniqueness collision (duplicate username, second
// admin during /v1/setup). The API maps it to 409.
var ErrConflict = errors.New("conflict")

// ErrNotFound covers any missing row — instance, user, or session. The API
// maps it to 404 (or 401 for sessions; the auth middleware translates).
var ErrNotFound = errors.New("not found")

type Store struct{ db *sql.DB }

func Open(path string) (*Store, error) {
	db, err := sql.Open("sqlite", path)
	if err != nil {
		return nil, err
	}
	db.SetMaxOpenConns(1) // sqlite: serialize writers, avoid "database is locked"
	if _, err := db.Exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;`); err != nil {
		return nil, err
	}
	s := &Store{db: db}
	if err := s.migrate(); err != nil {
		return nil, err
	}
	return s, nil
}

func (s *Store) Close() error { return s.db.Close() }

func (s *Store) migrate() error {
	_, err := s.db.Exec(`
		CREATE TABLE IF NOT EXISTS instances (
			id          TEXT PRIMARY KEY,
			manifest_id TEXT NOT NULL,
			name        TEXT NOT NULL,
			slug        TEXT NOT NULL UNIQUE,
			version     TEXT NOT NULL,
			state       TEXT NOT NULL,
			mdns_name   TEXT NOT NULL DEFAULT '',
			owner_user_id TEXT NOT NULL DEFAULT '',
			scope         TEXT NOT NULL DEFAULT 'household' CHECK (scope IN ('household','personal')),
			service_uid INTEGER NOT NULL DEFAULT 0,
			service_gid INTEGER NOT NULL DEFAULT 0,
			pending_recreate INTEGER NOT NULL DEFAULT 0,
			exposure    TEXT NOT NULL DEFAULT 'public' CHECK (exposure IN ('public','restricted')),
			created_at  INTEGER NOT NULL
		);
		CREATE TABLE IF NOT EXISTS instance_images (
			instance_id TEXT NOT NULL,
			service     TEXT NOT NULL,
			image       TEXT NOT NULL,
			digest      TEXT NOT NULL,
			PRIMARY KEY (instance_id, service),
			FOREIGN KEY (instance_id) REFERENCES instances(id) ON DELETE CASCADE
		);
		CREATE TABLE IF NOT EXISTS instance_secrets (
			instance_id TEXT NOT NULL,
			name        TEXT NOT NULL,
			value       TEXT NOT NULL,
			PRIMARY KEY (instance_id, name),
			FOREIGN KEY (instance_id) REFERENCES instances(id) ON DELETE CASCADE
		);
		-- instance_config: per-instance user-supplied configuration values
		-- (APP_MANIFEST.md # D4). Keyed by the app's own env-var name (app_env);
		-- value is stamped verbatim into the compose-override environment. The
		-- secret flag marks values the read API must never return and the UI masks.
		-- Plaintext at rest (same trust model as instance_secrets; hardening
		-- deferred, NEXT.md # App-secret injection hardening). Cascades on uninstall.
		CREATE TABLE IF NOT EXISTS instance_config (
			instance_id TEXT    NOT NULL,
			app_env     TEXT    NOT NULL,
			value       TEXT    NOT NULL,
			secret      INTEGER NOT NULL DEFAULT 0,
			PRIMARY KEY (instance_id, app_env),
			FOREIGN KEY (instance_id) REFERENCES instances(id) ON DELETE CASCADE
		);
		-- instance_resource_limits: the per-instance cgroup limit policy applied
		-- to the app's main service (ENVIRONMENT.md # Per-instance resource
		-- limits). At most one row per instance; absence means uncapped burst,
		-- the default (APP_ISOLATION.md # Resource limits). memory_bytes maps to
		-- the container's HostConfig.Memory and nano_cpus to NanoCpus; 0 leaves
		-- that dimension uncapped. Cascades with the app instance so uninstall
		-- reclaims it.
		CREATE TABLE IF NOT EXISTS instance_resource_limits (
			instance_id  TEXT    PRIMARY KEY REFERENCES instances(id) ON DELETE CASCADE,
			memory_bytes INTEGER NOT NULL DEFAULT 0,
			nano_cpus    INTEGER NOT NULL DEFAULT 0
		);
		-- service_instances: one shared managed-service container per type+version
		-- (SERVICE_PROVISIONING.md # Tier 1). The brain spins these up lazily and
		-- owns the superuser credential it provisions per-app databases with. Not
		-- an app instance: no slug, owner, route, or mDNS. superuser_password is
		-- plaintext at rest (same trust model as instance_secrets; hardening
		-- deferred, NEXT.md # App-secret injection hardening).
		CREATE TABLE IF NOT EXISTS service_instances (
			kind               TEXT    NOT NULL,
			version            TEXT    NOT NULL,
			superuser_password TEXT    NOT NULL,
			state              TEXT    NOT NULL,
			created_at         INTEGER NOT NULL,
			PRIMARY KEY (kind, version)
		);
		-- service_grants: the per-app database+role the brain provisioned inside a
		-- service_instance (SERVICE_PROVISIONING.md # Provisioning protocol). One
		-- row per (app instance, logical service name); injected back as
		-- MOOSE_SERVICE_<NAME>_*. Cascades with the app instance so uninstall
		-- reclaims the bookkeeping (the DB/role drop is a separate docker-exec
		-- step in lifecycle). password is plaintext at rest, as above.
		CREATE TABLE IF NOT EXISTS service_grants (
			instance_id  TEXT NOT NULL,
			logical_name TEXT NOT NULL,
			kind         TEXT NOT NULL,
			version      TEXT NOT NULL,
			db_name      TEXT NOT NULL,
			role_name    TEXT NOT NULL,
			password     TEXT NOT NULL,
			PRIMARY KEY (instance_id, logical_name),
			FOREIGN KEY (instance_id) REFERENCES instances(id) ON DELETE CASCADE
		);
		-- instance_mail_bindings: which provider a mail-capable app sends
		-- through — at most one per instance; an unbound instance gets no
		-- MOOSE_MAIL_* vars at all. Cascades with the app instance, and with
		-- the provider so deleting a provider unbinds its apps (never the
		-- reverse — apps always survive provider deletion).
		CREATE TABLE IF NOT EXISTS instance_mail_bindings (
			instance_id TEXT PRIMARY KEY REFERENCES instances(id) ON DELETE CASCADE,
			provider_id TEXT NOT NULL REFERENCES mail_providers(id) ON DELETE CASCADE
		);
		CREATE TABLE IF NOT EXISTS users (
			id            TEXT PRIMARY KEY,
			username      TEXT NOT NULL UNIQUE,
			display_name  TEXT NOT NULL DEFAULT '',
			role          TEXT NOT NULL CHECK (role IN ('admin','member')),
			recovery_hash TEXT NOT NULL DEFAULT '',
			created_at    INTEGER NOT NULL
		);
		CREATE TABLE IF NOT EXISTS sessions (
			token          TEXT PRIMARY KEY,
			user_id        TEXT NOT NULL,
			created_at     INTEGER NOT NULL,
			last_seen_at   INTEGER NOT NULL,
			expires_at     INTEGER NOT NULL DEFAULT 0,
			elevated_until INTEGER NOT NULL DEFAULT 0,
			fa_token       TEXT NOT NULL DEFAULT '',
			FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
		);
		CREATE TABLE IF NOT EXISTS audit_events (
			id            INTEGER PRIMARY KEY AUTOINCREMENT,
			ts            INTEGER NOT NULL,
			actor_user_id TEXT    NULL REFERENCES users(id) ON DELETE SET NULL,
			actor_role    TEXT    NOT NULL,
			action        TEXT    NOT NULL,
			target_kind   TEXT    NULL,
			target_id     TEXT    NULL,
			source_ip     TEXT    NULL,
			success       INTEGER NOT NULL,
			metadata      TEXT    NULL
		);
		CREATE TRIGGER IF NOT EXISTS audit_events_no_update
			BEFORE UPDATE ON audit_events
			WHEN NOT (NEW.actor_user_id IS NULL AND OLD.actor_user_id IS NOT NULL
			          AND NEW.ts = OLD.ts AND NEW.actor_role = OLD.actor_role
			          AND NEW.action = OLD.action AND NEW.success = OLD.success)
			BEGIN SELECT RAISE(ABORT, 'audit_events is append-only'); END;
		CREATE TRIGGER IF NOT EXISTS audit_events_no_delete
			BEFORE DELETE ON audit_events
			BEGIN SELECT RAISE(ABORT, 'audit_events is append-only'); END;
		CREATE TABLE IF NOT EXISTS health_issues (
			id              TEXT    NOT NULL,
			instance_key    TEXT    NOT NULL DEFAULT '',
			category        TEXT    NOT NULL,
			severity        TEXT    NOT NULL,
			tier            INTEGER NOT NULL,
			blocks_writes   INTEGER NOT NULL,
			blocks_apps     INTEGER NOT NULL,
			blocks_users    INTEGER NOT NULL,
			summary         TEXT    NOT NULL,
			details         TEXT    NOT NULL DEFAULT '',
			raised_at       INTEGER NOT NULL,
			last_checked_at INTEGER NOT NULL,
			PRIMARY KEY (id, instance_key)
		);
		-- notifications: the dashboard notification center (NOTIFICATIONS.md).
		-- Mutable and prunable, unlike audit_events. The full spec shape is
		-- created up front so later slices (read-state, dismiss, the API) add
		-- behavior without a migration; read_at / dismissed_at stay NULL until
		-- those land. The partial unique index enforces the coalescing
		-- invariant: at most one *active* (non-dismissed) notification per
		-- dedup_key.
		CREATE TABLE IF NOT EXISTS notifications (
			id            INTEGER PRIMARY KEY AUTOINCREMENT,
			ts            INTEGER NOT NULL,
			category      TEXT    NOT NULL,
			severity      TEXT    NOT NULL,
			source_kind   TEXT    NOT NULL,
			source_id     TEXT    NOT NULL,
			dedup_key     TEXT    NOT NULL,
			audience      TEXT    NOT NULL,
			user_id       TEXT    NULL REFERENCES users(id) ON DELETE CASCADE,
			variant       TEXT    NOT NULL,
			summary       TEXT    NOT NULL,
			body          TEXT    NOT NULL DEFAULT '',
			action_label  TEXT    NOT NULL DEFAULT '',
			action_route  TEXT    NOT NULL DEFAULT '',
			read_at       INTEGER NULL,
			dismissed_at  INTEGER NULL,
			resolved_at   INTEGER NULL
		);
		CREATE UNIQUE INDEX IF NOT EXISTS notifications_active_dedup
			ON notifications(dedup_key) WHERE dismissed_at IS NULL;
		-- notification_reads: per-recipient read/dismiss state (NOTIFICATIONS.md
		-- # Read / unread / dismiss). A box-wide ('admins') notification is one
		-- row in notifications but read/unread *per admin*, so read state can't
		-- live on the notification row — it lives here, one row per (notification,
		-- user). Used uniformly for every audience (the row-level read_at/
		-- dismissed_at columns on notifications stay reserved). ON DELETE CASCADE
		-- on both FKs so pruning a notification or deleting a user cleans up.
		CREATE TABLE IF NOT EXISTS notification_reads (
			notification_id INTEGER NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,
			user_id         TEXT    NOT NULL REFERENCES users(id)         ON DELETE CASCADE,
			read_at         INTEGER NULL,
			dismissed_at    INTEGER NULL,
			PRIMARY KEY (notification_id, user_id)
		);
		-- notification_mutes: per-user, per-category mute (NOTIFICATIONS.md
		-- # Configuration). Presence of a row means the category is muted for that
		-- user; absence means on — "everything on by default", so a new user has no
		-- rows and sees everything. The (user_id, category) PK fully models the
		-- mute; unmute is a DELETE. Mute is a read-time filter (the list/count/
		-- mark-all queries exclude muted categories), never emit-time suppression:
		-- a box-wide 'admins'/'members' notification is one row shared by many
		-- recipients, so it can't be withheld per-user at write time. ON DELETE
		-- CASCADE cleans up when the user is deleted.
		CREATE TABLE IF NOT EXISTS notification_mutes (
			user_id   TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			category  TEXT NOT NULL,
			PRIMARY KEY (user_id, category)
		);
		-- box_meta: a tiny key/value table for singleton box-level facts that
		-- aren't per-instance and don't warrant their own table. Today it holds
		-- the hosted-profile provisioning identity (ENVIRONMENT.md # Provisioning):
		-- the box-id, the portal's assertion-verification key, and the SSO owner's
		-- portal account id + user-id. The appliance profile never writes a row, so
		-- the table stays empty there.
		CREATE TABLE IF NOT EXISTS box_meta (
			key   TEXT PRIMARY KEY,
			value TEXT NOT NULL
		);
		-- used_assertions: single-use ledger for portal SSO assertion nonces
		-- (jti). Replay protection is the box's job — the cloud only guarantees
		-- per-mint uniqueness — so the SSO handler records each accepted jti here
		-- and rejects a second use. Rows expire with the ~60s-lived token; the
		-- handler prunes past-expiry rows on each write so the table stays tiny.
		-- Hosted-only; appliance never writes a row.
		CREATE TABLE IF NOT EXISTS used_assertions (
			jti        TEXT PRIMARY KEY,
			expires_at INTEGER NOT NULL
		);
		-- elevation_challenges: one-time confirm nonces for the hosted
		-- re-auth path (AUTH.md # Re-authentication for destructive actions).
		-- A hosted owner has no box password to re-type, so the confirm step is
		-- a portal round-trip; the dashboard mints a row here first and carries
		-- its id through the portal, which proves the round-trip was started by
		-- the box's own dashboard and not by a cross-site page. Single-use (the
		-- row is deleted when spent) and short-lived; each mint prunes
		-- past-expiry rows so the table stays tiny. Hosted-only; appliance never
		-- writes a row.
		CREATE TABLE IF NOT EXISTS elevation_challenges (
			id         TEXT PRIMARY KEY,
			user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			expires_at INTEGER NOT NULL
		);
		CREATE TABLE IF NOT EXISTS ssh_access (
			user_id          TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
			enabled          INTEGER NOT NULL DEFAULT 0,
			require_password INTEGER NOT NULL DEFAULT 0,
			updated_at       INTEGER NOT NULL
		);
		CREATE TABLE IF NOT EXISTS ssh_keys (
			id          TEXT PRIMARY KEY,
			user_id     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			label       TEXT NOT NULL DEFAULT '',
			public_key  TEXT NOT NULL,
			fingerprint TEXT NOT NULL,
			added_at    INTEGER NOT NULL,
			UNIQUE (user_id, fingerprint)
		);`)
	if err != nil {
		return err
	}
	// mail_providers is created from the same DDL the owner migration rebuilds
	// it with (mailProvidersDDL), so a fresh box and a migrated box end up with
	// one schema. instance_mail_bindings above references it before it exists,
	// which SQLite allows: a foreign key is resolved when it is used.
	if _, err := s.db.Exec(mailProvidersDDL("IF NOT EXISTS mail_providers")); err != nil {
		return err
	}
	// AI provider accounts (aiaccounts.go). A new table, so a box that
	// predates it just gets it created here.
	if _, err := s.db.Exec(aiAccountsDDL); err != nil {
		return err
	}

	// Idempotent migrations: add new columns when an older DB predates them.
	// SQLite doesn't support IF NOT EXISTS on ALTER TABLE; we detect existence
	// by probing PRAGMA table_info and skip if the column is already there.
	for _, col := range []struct {
		table string
		name  string
		stmt  string
	}{
		{"sessions", "expires_at", "ALTER TABLE sessions ADD COLUMN expires_at INTEGER NOT NULL DEFAULT 0"},
		{"sessions", "elevated_until", "ALTER TABLE sessions ADD COLUMN elevated_until INTEGER NOT NULL DEFAULT 0"},
		{"sessions", "fa_token", "ALTER TABLE sessions ADD COLUMN fa_token TEXT NOT NULL DEFAULT ''"},
		{"instances", "owner_user_id", "ALTER TABLE instances ADD COLUMN owner_user_id TEXT NOT NULL DEFAULT ''"},
		{"instances", "scope", "ALTER TABLE instances ADD COLUMN scope TEXT NOT NULL DEFAULT 'household'"},
		{"instances", "service_uid", "ALTER TABLE instances ADD COLUMN service_uid INTEGER NOT NULL DEFAULT 0"},
		{"instances", "service_gid", "ALTER TABLE instances ADD COLUMN service_gid INTEGER NOT NULL DEFAULT 0"},
		{"instances", "pending_recreate", "ALTER TABLE instances ADD COLUMN pending_recreate INTEGER NOT NULL DEFAULT 0"},
		{"instances", "exposure", "ALTER TABLE instances ADD COLUMN exposure TEXT NOT NULL DEFAULT 'public'"},
		{"mail_providers", "provider_type", "ALTER TABLE mail_providers ADD COLUMN provider_type TEXT NOT NULL DEFAULT 'custom'"},
		{"users", "display_name", "ALTER TABLE users ADD COLUMN display_name TEXT NOT NULL DEFAULT ''"},
	} {
		has, hErr := s.hasColumn(col.table, col.name)
		if hErr != nil {
			return hErr
		}
		if !has {
			if _, err := s.db.Exec(col.stmt); err != nil {
				return err
			}
		}
	}

	// Email accounts gained an owner (INSTALL_SETUP.md # 5). Runs after the
	// ALTER loop, so a very old table has its provider_type column by now.
	if err := s.migrateMailProviderOwners(); err != nil {
		return fmt.Errorf("migrate mail_providers owners: %w", err)
	}

	// Index the hosted forward-auth token (issue #305) for its per-request reverse
	// lookup (GetSessionByForwardAuthToken, called by the box Caddy's forward_auth
	// on every restricted-app request). Partial on fa_token != '' so it stays tiny —
	// only hosted rows carry a token; every appliance / pre-mint row has the ''
	// default and is excluded. Created after the ALTER loop so the column exists on
	// a migrated DB too.
	if _, err := s.db.Exec(
		`CREATE INDEX IF NOT EXISTS idx_sessions_fa_token ON sessions(fa_token) WHERE fa_token != ''`,
	); err != nil {
		return err
	}

	// Backfill expires_at = created_at + 90 days for rows that have the default 0.
	const ninetyDays = 90 * 24 * 60 * 60 // seconds
	if _, err := s.db.Exec(
		`UPDATE sessions SET expires_at = created_at + ? WHERE expires_at = 0`, ninetyDays,
	); err != nil {
		return err
	}

	// Backfill owner_user_id for instances installed before owner-scoping: assign
	// the bootstrap admin (oldest admin) so legacy rows have a valid owner. New
	// rows always carry an explicit owner from the install transaction.
	if _, err := s.db.Exec(
		`UPDATE instances SET owner_user_id = (SELECT id FROM users WHERE role='admin' ORDER BY created_at LIMIT 1)
		 WHERE owner_user_id = '' AND EXISTS (SELECT 1 FROM users WHERE role='admin')`,
	); err != nil {
		return err
	}

	// Backfill display_name for accounts created before the box had one, so a
	// migrated box shows a name rather than a blank where a name goes. The
	// account name is the only thing we know about those rows, and it is what
	// the dashboard was already showing them as.
	if _, err := s.db.Exec(
		`UPDATE users SET display_name = username WHERE display_name = ''`,
	); err != nil {
		return err
	}

	// The backfill above copies usernames, which are unique case-SENSITIVELY:
	// nothing ever stopped a box having both "Bob" and "bob", since the old
	// validateUsername rejected only "--" and an "xn--" prefix. Both would land
	// on display names the NOCASE index below treats as one, so it would fail to
	// build, migrate would error, and the brain would not start after the
	// upgrade. Resolve the collisions first.
	if err := s.dedupeDisplayNames(); err != nil {
		return err
	}

	// Display names are unique (FIRST_RUN.md # Identity & display names): two
	// people called Cindy on one box is the confusing case the spec rejects at
	// creation time. This index is the backstop, not the check. NOCASE only
	// folds ASCII, so the real comparison is the Unicode-aware one the API does
	// before it writes.
	if _, err := s.db.Exec(
		`CREATE UNIQUE INDEX IF NOT EXISTS idx_users_display_name ON users(display_name COLLATE NOCASE)`,
	); err != nil {
		return err
	}

	return nil
}

// dedupeDisplayNames makes display names unique ignoring case, renaming the
// later of any two that clash. Oldest account keeps the name it has; the next
// becomes "Bob 2", then "Bob 3", which is the shape the spec suggests to an
// admin who hits the same clash by hand (FIRST_RUN.md # Identity & display
// names).
//
// Only migrating boxes can need this: every new row goes through the API's own
// uniqueness check. It is idempotent, so a second startup finds nothing to do.
//
// Comparison is Go's Unicode-aware lowercase, which folds strictly more than
// the NOCASE index does. Erring that way is the safe direction: anything NOCASE
// would call a clash, this already renamed.
func (s *Store) dedupeDisplayNames() error {
	rows, err := s.db.Query(`SELECT id, display_name FROM users ORDER BY created_at, id`)
	if err != nil {
		return err
	}
	type row struct{ id, name string }
	var all []row
	for rows.Next() {
		var r row
		if err := rows.Scan(&r.id, &r.name); err != nil {
			rows.Close()
			return err
		}
		all = append(all, r)
	}
	rows.Close()
	if err := rows.Err(); err != nil {
		return err
	}

	taken := make(map[string]bool, len(all))
	for _, r := range all {
		candidate := r.name
		for n := 2; taken[strings.ToLower(candidate)]; n++ {
			candidate = fmt.Sprintf("%s %d", r.name, n)
		}
		taken[strings.ToLower(candidate)] = true
		if candidate == r.name {
			continue
		}
		if _, err := s.db.Exec(`UPDATE users SET display_name=? WHERE id=?`, candidate, r.id); err != nil {
			return err
		}
		slog.Warn("display name renamed to keep names unique on this box",
			"user_id", r.id, "from", r.name, "name", candidate)
	}
	return nil
}

// hasColumn reports whether table has a column of the given name.
func (s *Store) hasColumn(table, name string) (bool, error) {
	rows, err := s.db.Query(`PRAGMA table_info(` + table + `)`)
	if err != nil {
		return false, err
	}
	defer rows.Close()
	for rows.Next() {
		var cid, notnull, pk int
		var cname, ctype string
		var dflt any
		if err := rows.Scan(&cid, &cname, &ctype, &notnull, &dflt, &pk); err != nil {
			return false, err
		}
		if cname == name {
			return true, nil
		}
	}
	return false, rows.Err()
}

// InstanceImage is the resolved image pin for one service in one instance
// (APP_LIFECYCLE.md # image digest pinning).
type InstanceImage struct {
	Service string
	Image   string // original `image:tag` reference from the author's compose
	Digest  string // `sha256:…`
}

// SetInstanceImages replaces the pinned images for an instance in one
// transaction. Called once per install (and later, per update) after digests
// have been resolved.
func (s *Store) SetInstanceImages(instanceID string, images []InstanceImage) error {
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()
	if _, err := tx.Exec(`DELETE FROM instance_images WHERE instance_id=?`, instanceID); err != nil {
		return err
	}
	for _, img := range images {
		if _, err := tx.Exec(
			`INSERT INTO instance_images (instance_id, service, image, digest) VALUES (?,?,?,?)`,
			instanceID, img.Service, img.Image, img.Digest); err != nil {
			return err
		}
	}
	return tx.Commit()
}

// GetInstanceImages returns the pinned images for an instance, ordered by
// service name.
func (s *Store) GetInstanceImages(instanceID string) ([]InstanceImage, error) {
	rows, err := s.db.Query(
		`SELECT service, image, digest FROM instance_images
		 WHERE instance_id=? ORDER BY service`, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []InstanceImage
	for rows.Next() {
		var i InstanceImage
		if err := rows.Scan(&i.Service, &i.Image, &i.Digest); err != nil {
			return nil, err
		}
		out = append(out, i)
	}
	return out, rows.Err()
}

// InstanceSecret is one generated per-app secret (SERVICE_PROVISIONING.md #
// Env-var injection). Name is the manifest-declared snake_case key; Value is
// the generated, encoded secret the brain re-emits as MOOSE_SECRET_<NAME>.
type InstanceSecret struct {
	Name  string
	Value string
}

// SetInstanceSecrets persists an instance's generated secrets in one
// transaction. Called once per install, after the rows are generated. The
// values are written verbatim (plaintext at rest — the .env on disk holds the
// same value; row-level encryption is deferred, NEXT.md # App-secret injection
// hardening).
func (s *Store) SetInstanceSecrets(instanceID string, secrets []InstanceSecret) error {
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()
	if _, err := tx.Exec(`DELETE FROM instance_secrets WHERE instance_id=?`, instanceID); err != nil {
		return err
	}
	for _, sec := range secrets {
		if _, err := tx.Exec(
			`INSERT INTO instance_secrets (instance_id, name, value) VALUES (?,?,?)`,
			instanceID, sec.Name, sec.Value); err != nil {
			return err
		}
	}
	return tx.Commit()
}

// GetInstanceSecrets returns an instance's generated secrets, ordered by name.
func (s *Store) GetInstanceSecrets(instanceID string) ([]InstanceSecret, error) {
	rows, err := s.db.Query(
		`SELECT name, value FROM instance_secrets
		 WHERE instance_id=? ORDER BY name`, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []InstanceSecret
	for rows.Next() {
		var sec InstanceSecret
		if err := rows.Scan(&sec.Name, &sec.Value); err != nil {
			return nil, err
		}
		out = append(out, sec)
	}
	return out, rows.Err()
}

// InstanceConfig is one user-supplied config value (APP_MANIFEST.md # D4).
// AppEnv is the app's own env-var name (the storage key and the variable stamped
// into the compose override); Value is the user's answer; Secret marks values
// the read API must never return and the UI masks.
type InstanceConfig struct {
	AppEnv string
	Value  string
	Secret bool
}

// SetInstanceConfig replaces an instance's stored config values in one
// transaction. Called at install and on every post-install config edit. Values
// are written verbatim (plaintext at rest — the compose override on disk holds
// the same value; row-level encryption is deferred, NEXT.md # App-secret
// injection hardening).
func (s *Store) SetInstanceConfig(instanceID string, cfg []InstanceConfig) error {
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()
	if _, err := tx.Exec(`DELETE FROM instance_config WHERE instance_id=?`, instanceID); err != nil {
		return err
	}
	for _, c := range cfg {
		if _, err := tx.Exec(
			`INSERT INTO instance_config (instance_id, app_env, value, secret) VALUES (?,?,?,?)`,
			instanceID, c.AppEnv, c.Value, c.Secret); err != nil {
			return err
		}
	}
	return tx.Commit()
}

// GetInstanceConfig returns an instance's stored config values, ordered by
// app_env.
func (s *Store) GetInstanceConfig(instanceID string) ([]InstanceConfig, error) {
	rows, err := s.db.Query(
		`SELECT app_env, value, secret FROM instance_config
		 WHERE instance_id=? ORDER BY app_env`, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []InstanceConfig
	for rows.Next() {
		var c InstanceConfig
		if err := rows.Scan(&c.AppEnv, &c.Value, &c.Secret); err != nil {
			return nil, err
		}
		out = append(out, c)
	}
	return out, rows.Err()
}

// ServiceInstance is one shared managed-service container the brain runs
// (SERVICE_PROVISIONING.md # Tier 1). Kind+Version identify it (e.g.
// postgres/15); SuperuserPassword is the credential the brain provisions per-app
// databases with via docker exec.
type ServiceInstance struct {
	Kind              string
	Version           string
	SuperuserPassword string
	State             string // running
	CreatedAt         time.Time
}

// GetServiceInstance returns the service instance of a given kind+version, or
// ErrNotFound when none has been spun up yet (the lazy-spinup trigger).
func (s *Store) GetServiceInstance(kind, version string) (ServiceInstance, error) {
	var si ServiceInstance
	var created int64
	err := s.db.QueryRow(
		`SELECT kind, version, superuser_password, state, created_at
		 FROM service_instances WHERE kind=? AND version=?`, kind, version,
	).Scan(&si.Kind, &si.Version, &si.SuperuserPassword, &si.State, &created)
	if errors.Is(err, sql.ErrNoRows) {
		return ServiceInstance{}, ErrNotFound
	}
	if err != nil {
		return ServiceInstance{}, fmt.Errorf("scan service_instance: %w", err)
	}
	si.CreatedAt = time.Unix(created, 0)
	return si, nil
}

// CreateServiceInstance records a freshly spun-up service instance. Caller
// generates the superuser password.
func (s *Store) CreateServiceInstance(si ServiceInstance) error {
	_, err := s.db.Exec(
		`INSERT INTO service_instances (kind, version, superuser_password, state, created_at)
		 VALUES (?,?,?,?,?)`,
		si.Kind, si.Version, si.SuperuserPassword, si.State, si.CreatedAt.Unix())
	if err != nil && isUniqueErr(err) {
		return ErrConflict
	}
	return err
}

// ListServiceInstances returns every recorded service instance, used by the
// startup reconcile pass to re-assert each is running.
func (s *Store) ListServiceInstances() ([]ServiceInstance, error) {
	rows, err := s.db.Query(
		`SELECT kind, version, superuser_password, state, created_at
		 FROM service_instances ORDER BY kind, version`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []ServiceInstance
	for rows.Next() {
		var si ServiceInstance
		var created int64
		if err := rows.Scan(&si.Kind, &si.Version, &si.SuperuserPassword, &si.State, &created); err != nil {
			return nil, err
		}
		si.CreatedAt = time.Unix(created, 0)
		out = append(out, si)
	}
	return out, rows.Err()
}

// ServiceGrant is one per-app database+role provisioned inside a service
// instance (SERVICE_PROVISIONING.md # Per-app isolation). LogicalName is the
// manifest's `services:` map key; the brain re-emits the credentials as
// MOOSE_SERVICE_<LogicalName>_*.
type ServiceGrant struct {
	LogicalName string
	Kind        string
	Version     string
	DBName      string
	RoleName    string
	Password    string
}

// SetServiceGrants replaces an instance's service grants in one transaction.
// Called once per install after the databases+roles are provisioned. Mirrors
// SetInstanceSecrets.
func (s *Store) SetServiceGrants(instanceID string, grants []ServiceGrant) error {
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()
	if _, err := tx.Exec(`DELETE FROM service_grants WHERE instance_id=?`, instanceID); err != nil {
		return err
	}
	for _, g := range grants {
		if _, err := tx.Exec(
			`INSERT INTO service_grants
			 (instance_id, logical_name, kind, version, db_name, role_name, password)
			 VALUES (?,?,?,?,?,?,?)`,
			instanceID, g.LogicalName, g.Kind, g.Version, g.DBName, g.RoleName, g.Password); err != nil {
			return err
		}
	}
	return tx.Commit()
}

// GetServiceGrants returns an instance's service grants, ordered by logical name.
func (s *Store) GetServiceGrants(instanceID string) ([]ServiceGrant, error) {
	rows, err := s.db.Query(
		`SELECT logical_name, kind, version, db_name, role_name, password
		 FROM service_grants WHERE instance_id=? ORDER BY logical_name`, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []ServiceGrant
	for rows.Next() {
		var g ServiceGrant
		if err := rows.Scan(&g.LogicalName, &g.Kind, &g.Version, &g.DBName, &g.RoleName, &g.Password); err != nil {
			return nil, err
		}
		out = append(out, g)
	}
	return out, rows.Err()
}

func (s *Store) Create(i Instance) error {
	// Defense-in-depth: fresh DBs carry a CHECK on scope, but SQLite can't add a
	// CHECK via the ALTER-TABLE migration path, so a DB created before this
	// column has no constraint. Enforce the invariant here so neither path can
	// persist an out-of-range scope (which canSee would silently treat as unseen).
	if i.Scope != ScopeHousehold && i.Scope != ScopePersonal {
		return fmt.Errorf("invalid instance scope %q", i.Scope)
	}
	// Same defense-in-depth as scope: the ALTER-migration path can't carry the
	// CHECK, so normalize an unset exposure to public and reject anything else
	// before it reaches the row. Empty must not be inserted verbatim — it would
	// violate the fresh-DB CHECK (the column is written explicitly, so the DDL
	// DEFAULT never applies to a Create).
	if i.Exposure == "" {
		i.Exposure = ExposurePublic
	}
	if i.Exposure != ExposurePublic && i.Exposure != ExposureRestricted {
		return fmt.Errorf("invalid instance exposure %q", i.Exposure)
	}
	_, err := s.db.Exec(
		`INSERT INTO instances (id, manifest_id, name, slug, version, state, mdns_name, owner_user_id, scope, service_uid, service_gid, exposure, created_at)
		 VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`,
		i.ID, i.ManifestID, i.Name, i.Slug, i.Version, i.State, i.MDNSName, i.OwnerUserID, i.Scope, i.ServiceUID, i.ServiceGID, i.Exposure, i.CreatedAt.Unix())
	return err
}

func (s *Store) SetState(id, state string) error {
	res, err := s.db.Exec(`UPDATE instances SET state=? WHERE id=?`, state, id)
	if err != nil {
		return err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return ErrNotFound
	}
	return nil
}

func (s *Store) SetMDNSName(id, name string) error {
	_, err := s.db.Exec(`UPDATE instances SET mdns_name=? WHERE id=?`, name, id)
	return err
}

// SetServiceIdentity persists the allocated app-service UID/GID on the
// instance row (APP_ISOLATION.md # Runtime identity & data ownership). Written
// once at install, read back for release at uninstall; never re-rolled — a
// transient identity would orphan the data it owns.
func (s *Store) SetServiceIdentity(id string, uid, gid int) error {
	res, err := s.db.Exec(`UPDATE instances SET service_uid=?, service_gid=? WHERE id=?`, uid, gid, id)
	if err != nil {
		return err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return ErrNotFound
	}
	return nil
}

// SetInstancePendingRecreate marks (or clears) an instance's owed-recreate flag
// (#268). The reconcile pass recreates a running container while this is set —
// the recovery path when an env-restamping edit (config or mail) committed the
// override/.env but its follow-up `compose up` failed, stranding the container
// on stale env — and clears it once a recreate succeeds.
func (s *Store) SetInstancePendingRecreate(id string, pending bool) error {
	v := 0
	if pending {
		v = 1
	}
	res, err := s.db.Exec(`UPDATE instances SET pending_recreate=? WHERE id=?`, v, id)
	if err != nil {
		return err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return ErrNotFound
	}
	return nil
}

// SetInstanceExposure flips an app's access gate between ExposurePublic and
// ExposureRestricted (#306, the hosted per-app Only-me / Public toggle). Desired
// state — the lifecycle re-applies the Caddy route from it. Rejects an
// out-of-range value so the reconcile route builder can trust the column.
func (s *Store) SetInstanceExposure(id, exposure string) error {
	if exposure != ExposurePublic && exposure != ExposureRestricted {
		return fmt.Errorf("invalid instance exposure %q", exposure)
	}
	res, err := s.db.Exec(`UPDATE instances SET exposure=? WHERE id=?`, exposure, id)
	if err != nil {
		return err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return ErrNotFound
	}
	return nil
}

func (s *Store) Delete(id string) error {
	_, err := s.db.Exec(`DELETE FROM instances WHERE id=?`, id)
	return err
}

const instanceColumns = `id, manifest_id, name, slug, version, state, mdns_name, owner_user_id, scope, service_uid, service_gid, pending_recreate, exposure, created_at`

func (s *Store) Get(id string) (Instance, error) {
	return scan(s.db.QueryRow(
		`SELECT `+instanceColumns+` FROM instances WHERE id=?`, id))
}

func (s *Store) List() ([]Instance, error) {
	return s.queryInstances(`SELECT ` + instanceColumns + ` FROM instances ORDER BY created_at`)
}

// ListVisibleTo returns the instances a caller may see on the home grid
// (DASHBOARD.md # the home screen): all household instances plus the caller's
// own personal instances. An admin sees every instance. Per-app member grants
// for household apps are deferred (NEXT.md), so household apps are visible to
// all members for now.
//
// The WHERE clause below is the SQL twin of api.canSee's single-instance
// predicate — KEEP THE TWO IN SYNC. When per-app member grants land, both must
// change together (there is no compile-time link between them).
func (s *Store) ListVisibleTo(userID string, isAdmin bool) ([]Instance, error) {
	if isAdmin {
		return s.List()
	}
	return s.queryInstances(
		`SELECT `+instanceColumns+` FROM instances
		 WHERE scope='household' OR owner_user_id=? ORDER BY created_at`, userID)
}

// InstancesByManifest returns every instance of a given manifest, regardless of
// owner. The install handler uses it to detect duplicates for the
// warn-don't-block flow (DASHBOARD.md # warn, don't block).
func (s *Store) InstancesByManifest(manifestID string) ([]Instance, error) {
	return s.queryInstances(
		`SELECT `+instanceColumns+` FROM instances WHERE manifest_id=? ORDER BY created_at`, manifestID)
}

func (s *Store) queryInstances(query string, args ...any) ([]Instance, error) {
	rows, err := s.db.Query(query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []Instance
	for rows.Next() {
		i, err := scan(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, i)
	}
	return out, rows.Err()
}

// SlugTaken reports whether a slug is already used by an installed instance.
func (s *Store) SlugTaken(slug string) (bool, error) {
	var n int
	err := s.db.QueryRow(`SELECT COUNT(*) FROM instances WHERE slug=?`, slug).Scan(&n)
	return n > 0, err
}

// CreateUser inserts a user row. Returns ErrConflict on a duplicate username or
// a duplicate display name.
func (s *Store) CreateUser(u User) error {
	if err := requireDisplayName(u); err != nil {
		return err
	}
	_, err := s.db.Exec(
		`INSERT INTO users (id, username, display_name, role, recovery_hash, created_at) VALUES (?,?,?,?,?,?)`,
		u.ID, u.Username, u.DisplayName, u.Role, u.RecoveryHash, u.CreatedAt.Unix())
	if err != nil && isUniqueErr(err) {
		return ErrConflict
	}
	return err
}

// requireDisplayName rejects a user row with no display name. Every surface
// renders the display name, so a blank one is a caller bug, and the unique index
// would otherwise turn it into a confusing conflict on the *second* such insert
// rather than an error on the first.
func requireDisplayName(u User) error {
	if u.DisplayName == "" {
		return fmt.Errorf("user %q: display name is required", u.Username)
	}
	return nil
}

// CreateFirstAdmin inserts an admin user iff the users table is empty. Used
// by /v1/setup to atomically bootstrap the box and lose any race between two
// callers — the loser gets ErrConflict. Single transaction.
func (s *Store) CreateFirstAdmin(u User) error {
	if u.Role != RoleAdmin {
		return fmt.Errorf("CreateFirstAdmin: role must be admin, got %q", u.Role)
	}
	if err := requireDisplayName(u); err != nil {
		return err
	}
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()
	var n int
	if err := tx.QueryRow(`SELECT COUNT(*) FROM users`).Scan(&n); err != nil {
		return err
	}
	if n > 0 {
		return ErrConflict
	}
	if _, err := tx.Exec(
		`INSERT INTO users (id, username, display_name, role, recovery_hash, created_at) VALUES (?,?,?,?,?,?)`,
		u.ID, u.Username, u.DisplayName, u.Role, u.RecoveryHash, u.CreatedAt.Unix()); err != nil {
		if isUniqueErr(err) {
			return ErrConflict
		}
		return err
	}
	return tx.Commit()
}

func (s *Store) GetUser(id string) (User, error) {
	return scanUser(s.db.QueryRow(
		`SELECT id, username, display_name, role, recovery_hash, created_at FROM users WHERE id=?`, id))
}

func (s *Store) GetUserByUsername(username string) (User, error) {
	return scanUser(s.db.QueryRow(
		`SELECT id, username, display_name, role, recovery_hash, created_at FROM users WHERE username=?`, username))
}

func (s *Store) ListUsers() ([]User, error) {
	rows, err := s.db.Query(
		`SELECT id, username, display_name, role, recovery_hash, created_at FROM users ORDER BY created_at`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []User
	for rows.Next() {
		u, err := scanUser(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, u)
	}
	return out, rows.Err()
}

func (s *Store) DeleteUser(id string) error {
	res, err := s.db.Exec(`DELETE FROM users WHERE id=?`, id)
	if err != nil {
		return err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return ErrNotFound
	}
	return nil
}

// UpdateDisplayName changes what every surface shows for a user. It touches
// nothing else on purpose: the account name, the home directory, and file
// ownership are frozen at creation (FIRST_RUN.md # Identity & display names).
// Returns ErrNotFound when no such user exists, ErrConflict when another
// account already uses the name.
func (s *Store) UpdateDisplayName(id, name string) error {
	res, err := s.db.Exec(`UPDATE users SET display_name=? WHERE id=?`, name, id)
	if err != nil {
		if isUniqueErr(err) {
			return ErrConflict
		}
		return err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return ErrNotFound
	}
	return nil
}

// UpdateRole changes a user's role. Returns ErrNotFound when no such user exists.
func (s *Store) UpdateRole(id, role string) error {
	if role != RoleAdmin && role != RoleMember {
		return fmt.Errorf("invalid role %q", role)
	}
	res, err := s.db.Exec(`UPDATE users SET role=? WHERE id=?`, role, id)
	if err != nil {
		return err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return ErrNotFound
	}
	return nil
}

// UpdateRecoveryHash replaces the recovery_hash for a user in-place. Used by
// /v1/recover to rotate the old code after a successful redemption. Returns
// ErrNotFound when no such user exists.
func (s *Store) UpdateRecoveryHash(userID, newHash string) error {
	res, err := s.db.Exec(`UPDATE users SET recovery_hash=? WHERE id=?`, newHash, userID)
	if err != nil {
		return err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return ErrNotFound
	}
	return nil
}

// CountAdmins returns the number of users with role="admin".
func (s *Store) CountAdmins() (int, error) {
	var n int
	err := s.db.QueryRow(`SELECT COUNT(*) FROM users WHERE role='admin'`).Scan(&n)
	return n, err
}

// UserCount returns the total number of registered users.
func (s *Store) UserCount() (int, error) {
	var n int
	err := s.db.QueryRow(`SELECT COUNT(*) FROM users`).Scan(&n)
	return n, err
}

// HasAnyUser is the bootstrap probe: /v1/auth/state uses it to route the UI
// between /setup and /login.
func (s *Store) HasAnyUser() (bool, error) {
	n, err := s.UserCount()
	return n > 0, err
}

// Box-level metadata keys for the box_meta KV table. box_id and the assertion
// verification key are set on a hosted box from the first-boot seed
// (ENVIRONMENT.md # Provisioning) and absent on appliance; the SSO owner keys are
// recorded on the first valid portal assertion; telemetry consent and first-run
// completion are box-wide facts the first-run wizard records on both profiles
// (FIRST_RUN.md # Step 4, # Phase 3 / TELEMETRY.md).
const (
	BoxMetaBoxID = "box_id"
	// BoxMetaAssertionKey holds the portal's Ed25519 verification key (standard
	// base64) ingested from the seed, so later (frozen-identity) boots verify SSO
	// assertions without re-reading the seed the brain otherwise ignores. It
	// replaces the prior one-time admin-bootstrap secret hash.
	BoxMetaAssertionKey = "assertion_verification_key"
	// BoxMetaOwnerSub is the portal account id (assertion `sub`) of the box owner,
	// recorded on the first valid SSO assertion. v1 is owner-only: a later
	// assertion whose `sub` differs is rejected (cloud specs/AUTH_AND_ACCESS.md —
	// granting other accounts is deferred).
	BoxMetaOwnerSub = "sso_owner_sub"
	// BoxMetaOwnerUserID is the brain user-id of the auto-created owner admin, so
	// every subsequent owner assertion issues a session for the same account
	// rather than re-deriving it from the email.
	BoxMetaOwnerUserID = "sso_owner_user_id"
	// BoxMetaTelemetryConsent is "true"/"false"; unset ⇒ off (TELEMETRY.md
	// # Locked: off by default).
	BoxMetaTelemetryConsent = "telemetry_consent"
	// BoxMetaFirstRunComplete is "true" once the wizard's Done step runs; unset
	// ⇒ first-run incomplete. It gates the wizard's reappearance (FIRST_RUN.md
	// # Phase 3) and is distinct from "an admin exists" — completion is more
	// than the first POST /setup.
	BoxMetaFirstRunComplete = "first_run_complete"
	// BoxMetaEnrollment holds the per-box acme-dns credentials (JSON) ingested
	// from the seed, so later (frozen-identity) boots can reconfigure Caddy's
	// DNS-01 wildcard issuer without re-reading the seed the brain otherwise
	// ignores (ENVIRONMENT.md # Networking & discovery; C3b). Stored plaintext at
	// MVP, matching the cloud producer's posture — a leaked pair only lets an
	// attacker renew certs for this one box; at-rest encryption is a deferred
	// hardening item (NEXT.md).
	BoxMetaEnrollment = "acmedns_enrollment"
)

// GetBoxMeta returns the value stored under key, or ErrNotFound when unset.
func (s *Store) GetBoxMeta(key string) (string, error) {
	var v string
	err := s.db.QueryRow(`SELECT value FROM box_meta WHERE key=?`, key).Scan(&v)
	if errors.Is(err, sql.ErrNoRows) {
		return "", ErrNotFound
	}
	if err != nil {
		return "", fmt.Errorf("scan box_meta: %w", err)
	}
	return v, nil
}

// SetBoxMeta upserts a box-level metadata value. Idempotent: re-writing the
// same key with the same value is a no-op from the caller's view.
func (s *Store) SetBoxMeta(key, value string) error {
	_, err := s.db.Exec(
		`INSERT INTO box_meta (key, value) VALUES (?,?)
		 ON CONFLICT(key) DO UPDATE SET value=excluded.value`, key, value)
	return err
}

// UseAssertionJTI records a portal SSO assertion nonce as spent, enforcing
// single-use: a first insert returns nil, a second insert of the same jti
// returns ErrConflict (the replay signal the SSO handler maps to a rejection).
// expiresAt is the token's own Exp; pruning past-expiry rows here (now is the
// caller's clock) keeps the ledger bounded to roughly the in-flight token set,
// since accepted tokens are ~60s-lived. Pruning runs before the insert so a jti
// can never be evicted in the same call that records it.
func (s *Store) UseAssertionJTI(jti string, expiresAt, now time.Time) error {
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()
	if _, err := tx.Exec(`DELETE FROM used_assertions WHERE expires_at <= ?`, now.Unix()); err != nil {
		return err
	}
	if _, err := tx.Exec(
		`INSERT INTO used_assertions (jti, expires_at) VALUES (?,?)`,
		jti, expiresAt.Unix()); err != nil {
		if isUniqueErr(err) {
			return ErrConflict
		}
		return err
	}
	return tx.Commit()
}

// CreateElevationChallenge records a one-time confirm nonce for userID, to be
// spent by the SSO landing (UseElevationChallenge). Past-expiry rows are pruned
// on the way in — now is the caller's clock — so the table stays bounded by the
// in-flight set without a sweeper.
func (s *Store) CreateElevationChallenge(id, userID string, expiresAt, now time.Time) error {
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()
	if _, err := tx.Exec(`DELETE FROM elevation_challenges WHERE expires_at <= ?`, now.Unix()); err != nil {
		return err
	}
	if _, err := tx.Exec(
		`INSERT INTO elevation_challenges (id, user_id, expires_at) VALUES (?,?,?)`,
		id, userID, expiresAt.Unix()); err != nil {
		return err
	}
	return tx.Commit()
}

// UseElevationChallenge spends a confirm nonce and returns the user it was
// minted for. The row is deleted in the same transaction that reads it, so a
// replay of the same id finds nothing: ErrNotFound covers unknown, expired, and
// already-spent alike — the caller must not tell them apart to a client.
func (s *Store) UseElevationChallenge(id string, now time.Time) (string, error) {
	tx, err := s.db.Begin()
	if err != nil {
		return "", err
	}
	defer tx.Rollback()
	var userID string
	err = tx.QueryRow(
		`SELECT user_id FROM elevation_challenges WHERE id=? AND expires_at > ?`,
		id, now.Unix()).Scan(&userID)
	if errors.Is(err, sql.ErrNoRows) {
		return "", ErrNotFound
	}
	if err != nil {
		return "", fmt.Errorf("scan elevation_challenges: %w", err)
	}
	if _, err := tx.Exec(`DELETE FROM elevation_challenges WHERE id=?`, id); err != nil {
		return "", err
	}
	if err := tx.Commit(); err != nil {
		return "", err
	}
	return userID, nil
}

// CreateSession persists a freshly issued session. Caller picks the token.
func (s *Store) CreateSession(sess Session) error {
	_, err := s.db.Exec(
		`INSERT INTO sessions (token, user_id, created_at, last_seen_at, expires_at, elevated_until)
		 VALUES (?,?,?,?,?,?)`,
		sess.Token, sess.UserID, sess.CreatedAt.Unix(), sess.LastSeenAt.Unix(),
		sess.ExpiresAt.Unix(), sess.ElevatedUntil.Unix())
	return err
}

// GetSession looks up a session by its token. ErrNotFound on miss; the auth
// middleware maps that to 401.
func (s *Store) GetSession(token string) (Session, error) {
	var sess Session
	var created, lastSeen, expiresAt, elevatedUntil int64
	err := s.db.QueryRow(
		`SELECT token, user_id, created_at, last_seen_at, expires_at, elevated_until
		 FROM sessions WHERE token=?`, token,
	).Scan(&sess.Token, &sess.UserID, &created, &lastSeen, &expiresAt, &elevatedUntil)
	if errors.Is(err, sql.ErrNoRows) {
		return Session{}, ErrNotFound
	}
	if err != nil {
		return Session{}, fmt.Errorf("scan session: %w", err)
	}
	sess.CreatedAt = time.Unix(created, 0)
	sess.LastSeenAt = time.Unix(lastSeen, 0)
	sess.ExpiresAt = time.Unix(expiresAt, 0)
	sess.ElevatedUntil = time.Unix(elevatedUntil, 0)
	return sess, nil
}

// SetSessionForwardAuthToken stamps a session with its hosted forward-auth token
// (issue #305). The token is a second, lower-privilege credential the browser
// carries to app subdomains via a Domain-scoped cookie; storing it on the session
// row ties its lifetime to the session (logout / expiry drop it) and keeps it in a
// distinct column so it can never resolve as a dashboard session token. Hosted-only
// in practice — the appliance never mints one.
func (s *Store) SetSessionForwardAuthToken(sessionToken, faToken string) error {
	_, err := s.db.Exec(
		`UPDATE sessions SET fa_token=? WHERE token=?`, faToken, sessionToken)
	return err
}

// GetSessionByForwardAuthToken resolves a session from its forward-auth token, the
// reverse lookup the hosted forward-auth verify endpoint runs per request (#305).
// An empty faToken is rejected up front so it can never match the empty-string
// default that every non-hosted (and pre-mint) session row carries.
func (s *Store) GetSessionByForwardAuthToken(faToken string) (Session, error) {
	if faToken == "" {
		return Session{}, ErrNotFound
	}
	var sess Session
	var created, lastSeen, expiresAt, elevatedUntil int64
	err := s.db.QueryRow(
		`SELECT token, user_id, created_at, last_seen_at, expires_at, elevated_until
		 FROM sessions WHERE fa_token=?`, faToken,
	).Scan(&sess.Token, &sess.UserID, &created, &lastSeen, &expiresAt, &elevatedUntil)
	if errors.Is(err, sql.ErrNoRows) {
		return Session{}, ErrNotFound
	}
	if err != nil {
		return Session{}, fmt.Errorf("scan session by fa_token: %w", err)
	}
	sess.CreatedAt = time.Unix(created, 0)
	sess.LastSeenAt = time.Unix(lastSeen, 0)
	sess.ExpiresAt = time.Unix(expiresAt, 0)
	sess.ElevatedUntil = time.Unix(elevatedUntil, 0)
	return sess, nil
}

// SetElevatedUntil marks a session elevated until the given time. Used by the
// POST /api/v1/auth/elevate handler (USERS_AND_GROUPS.md # Elevation in the UI).
func (s *Store) SetElevatedUntil(token string, until time.Time) error {
	_, err := s.db.Exec(
		`UPDATE sessions SET elevated_until=? WHERE token=?`, until.Unix(), token)
	return err
}

// TouchSession updates last_seen_at — called by the auth middleware on every
// authenticated request.
func (s *Store) TouchSession(token string, at time.Time) error {
	_, err := s.db.Exec(`UPDATE sessions SET last_seen_at=? WHERE token=?`, at.Unix(), token)
	return err
}

// DeleteSession revokes a single session (logout).
func (s *Store) DeleteSession(token string) error {
	_, err := s.db.Exec(`DELETE FROM sessions WHERE token=?`, token)
	return err
}

// DeleteSessionsForUser revokes every session belonging to a user. Used after
// password reset and on user deletion (AUTH.md # Recovery).
func (s *Store) DeleteSessionsForUser(userID string) error {
	_, err := s.db.Exec(`DELETE FROM sessions WHERE user_id=?`, userID)
	return err
}

// ListSessionsForUser returns all sessions for a user, ordered by created_at.
// Used in tests to inspect session state without knowing the token.
func (s *Store) ListSessionsForUser(userID string) ([]Session, error) {
	rows, err := s.db.Query(
		`SELECT token, user_id, created_at, last_seen_at, expires_at, elevated_until
		 FROM sessions WHERE user_id=? ORDER BY created_at`, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []Session
	for rows.Next() {
		var sess Session
		var created, lastSeen, expiresAt, elevatedUntil int64
		if err := rows.Scan(&sess.Token, &sess.UserID, &created, &lastSeen, &expiresAt, &elevatedUntil); err != nil {
			return nil, err
		}
		sess.CreatedAt = time.Unix(created, 0)
		sess.LastSeenAt = time.Unix(lastSeen, 0)
		sess.ExpiresAt = time.Unix(expiresAt, 0)
		sess.ElevatedUntil = time.Unix(elevatedUntil, 0)
		out = append(out, sess)
	}
	return out, rows.Err()
}

func scanUser(row scanner) (User, error) {
	var u User
	var created int64
	err := row.Scan(&u.ID, &u.Username, &u.DisplayName, &u.Role, &u.RecoveryHash, &created)
	if errors.Is(err, sql.ErrNoRows) {
		return User{}, ErrNotFound
	}
	if err != nil {
		return User{}, fmt.Errorf("scan user: %w", err)
	}
	u.CreatedAt = time.Unix(created, 0)
	return u, nil
}

// AuditEvent is one row in the append-only audit log (LOGGING.md # Schema sketch).
// actor_user_id is NULL for system events; actor_role is 'system' in that case.
type AuditEvent struct {
	ID          int64
	TS          int64  // unix epoch ms
	ActorUserID string // empty when NULL
	ActorRole   string // "admin" | "member" | "system"
	Action      string
	TargetKind  string // empty when NULL
	TargetID    string // empty when NULL
	SourceIP    string // empty when NULL
	Success     bool
	Metadata    string // JSON text, empty when NULL
}

// InsertAuditEvent appends one row. The table's triggers prevent UPDATE/DELETE.
func (s *Store) InsertAuditEvent(e AuditEvent) error {
	var actorUserID any
	if e.ActorUserID != "" {
		actorUserID = e.ActorUserID
	}
	var targetKind, targetID, sourceIP, metadata any
	if e.TargetKind != "" {
		targetKind = e.TargetKind
	}
	if e.TargetID != "" {
		targetID = e.TargetID
	}
	if e.SourceIP != "" {
		sourceIP = e.SourceIP
	}
	if e.Metadata != "" {
		metadata = e.Metadata
	}
	success := 0
	if e.Success {
		success = 1
	}
	_, err := s.db.Exec(
		`INSERT INTO audit_events
		 (ts, actor_user_id, actor_role, action, target_kind, target_id, source_ip, success, metadata)
		 VALUES (?,?,?,?,?,?,?,?,?)`,
		e.TS, actorUserID, e.ActorRole, e.Action,
		targetKind, targetID, sourceIP, success, metadata)
	return err
}

// AuditFilter controls which rows ListAuditEvents returns.
type AuditFilter struct {
	// ActorUserID, when set, restricts to rows where actor_user_id = this value
	// OR (target_kind = 'user' AND target_id = this value). Used for member
	// visibility. Empty means "no restriction" (admin view).
	ActorUserID string
	AfterID     int64 // cursor: return rows with id < AfterID (0 = from newest)
	Limit       int
}

// ListAuditEvents returns rows newest-first, respecting the visibility filter.
func (s *Store) ListAuditEvents(f AuditFilter) ([]AuditEvent, error) {
	limit := f.Limit
	if limit <= 0 {
		limit = 50
	}

	var rows *sql.Rows
	var err error
	if f.ActorUserID != "" {
		// Member view: own actions or events targeting self.
		if f.AfterID > 0 {
			rows, err = s.db.Query(
				`SELECT id, ts, actor_user_id, actor_role, action, target_kind, target_id,
				        source_ip, success, metadata
				 FROM audit_events
				 WHERE id < ?
				   AND (actor_user_id = ? OR (target_kind = 'user' AND target_id = ?))
				 ORDER BY id DESC LIMIT ?`,
				f.AfterID, f.ActorUserID, f.ActorUserID, limit)
		} else {
			rows, err = s.db.Query(
				`SELECT id, ts, actor_user_id, actor_role, action, target_kind, target_id,
				        source_ip, success, metadata
				 FROM audit_events
				 WHERE actor_user_id = ? OR (target_kind = 'user' AND target_id = ?)
				 ORDER BY id DESC LIMIT ?`,
				f.ActorUserID, f.ActorUserID, limit)
		}
	} else {
		// Admin view: all rows.
		if f.AfterID > 0 {
			rows, err = s.db.Query(
				`SELECT id, ts, actor_user_id, actor_role, action, target_kind, target_id,
				        source_ip, success, metadata
				 FROM audit_events WHERE id < ? ORDER BY id DESC LIMIT ?`,
				f.AfterID, limit)
		} else {
			rows, err = s.db.Query(
				`SELECT id, ts, actor_user_id, actor_role, action, target_kind, target_id,
				        source_ip, success, metadata
				 FROM audit_events ORDER BY id DESC LIMIT ?`,
				limit)
		}
	}
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []AuditEvent
	for rows.Next() {
		e, err := scanAuditEvent(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, e)
	}
	return out, rows.Err()
}

func scanAuditEvent(row scanner) (AuditEvent, error) {
	var e AuditEvent
	var actorUserID, targetKind, targetID, sourceIP, metadata sql.NullString
	var success int
	err := row.Scan(
		&e.ID, &e.TS, &actorUserID, &e.ActorRole, &e.Action,
		&targetKind, &targetID, &sourceIP, &success, &metadata)
	if err != nil {
		return AuditEvent{}, fmt.Errorf("scan audit_event: %w", err)
	}
	e.ActorUserID = actorUserID.String
	e.TargetKind = targetKind.String
	e.TargetID = targetID.String
	e.SourceIP = sourceIP.String
	e.Metadata = metadata.String
	e.Success = success != 0
	return e, nil
}

// isUniqueErr matches modernc.org/sqlite's UNIQUE-constraint error without
// importing the driver's error type. modernc returns errors whose string
// contains "UNIQUE constraint failed".
func isUniqueErr(err error) bool {
	return err != nil && strings.Contains(err.Error(), "UNIQUE constraint failed")
}

type scanner interface{ Scan(dest ...any) error }

func scan(row scanner) (Instance, error) {
	var i Instance
	var created, pendingRecreate int64
	err := row.Scan(&i.ID, &i.ManifestID, &i.Name, &i.Slug, &i.Version, &i.State, &i.MDNSName, &i.OwnerUserID, &i.Scope, &i.ServiceUID, &i.ServiceGID, &pendingRecreate, &i.Exposure, &created)
	if errors.Is(err, sql.ErrNoRows) {
		return Instance{}, ErrNotFound
	}
	if err != nil {
		return Instance{}, fmt.Errorf("scan instance: %w", err)
	}
	i.PendingRecreate = pendingRecreate != 0
	i.CreatedAt = time.Unix(created, 0)
	return i, nil
}
